import express from "express";
import path from "path";
import { fileURLToPath } from "url";
import { GoogleGenerativeAI } from "@google/generative-ai";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
app.disable("x-powered-by");

const PORT = Number(process.env.PORT || 6969);

const encodedString = "QUl6YVN5Qnh2RWxDU0p4YW9NbUs3ZGtLNWxhcDlUZHJ4ZFM3VVY4";
const GEMINI_KEY = atob(encodedString)

app.use(express.json({ limit: "1mb" }));
app.use(express.static(path.join(__dirname, "public")));

const systemPrompt = `
You will be given a piece of text that sounds like it was generated by AI. Your task is to rewrite this text so it sounds more human-written while preserving the original meaning, structure, formatting, and overall intent.

STEP 1

First, confirm that you understand the instruction and ask the user to provide the text.

Once the user provides the text, read it carefully.

STEP 2 — REWRITING RULES

Rewrite the text while following ALL of these instructions.

FORMAT AND LENGTH REQUIREMENTS

Keep the same overall format as the original text.

If the original has paragraphs, return paragraphs in the same places.

If it has bullet points, return bullet points in similar places.

If it has headings or sections, keep the same structure.

Do not merge paragraphs, delete sections, or collapse lists.

NEW HARD LENGTH RULE

Your rewrite must be at least 50 words longer than the original text.

You must add length by:

using more natural phrasing,

adding small clarifying sentences,

adding transitions, and

lightly restating ideas in more human ways.

You must not:

add new arguments,

add new facts, or

change the meaning of anything.

If the result is not 50+ words longer, you must expand until it is.

WRITING STYLE REQUIREMENTS

Make the text feel like a real human wrote it by following these rules:

a) Use a conversational tone, concise language, and avoid complex jargon.
Example: “Hey friends, today I’ll show you a useful writing tip.”

b) Use short, punchy sentences when appropriate.
Example: “You walk in. Your heart sinks. The pressure hits.”

c) Use simple language. Aim for 7th-grade readability or lower.
Example: “Emails help businesses talk to customers.”

d) Use occasional rhetorical fragments to improve flow.
Example: “The good news? My three-step process works for most businesses.”

e) Use bullet points when relevant, similar to the original formatting.

f) Use analogies or examples when helpful.
Example: “Creating an email course with AI feels easier than basic math.”

g) Split long sentences into shorter ones.

h) Include brief personal anecdotes only if the original tone is reflective or narrative. Do not invent stories for formal or technical text.

i) Use bold and italic formatting to emphasize key words.
Do this with normal text formatting, not Markdown or asterisks.

j) Do NOT use emojis or hashtags.

k) Avoid overly promotional words like:
game-changing, unlock, master, skyrocket, revolutionize.

FOLLOW THIS WRITING STYLE

Your rewrite SHOULD:

Use clear, simple language.

Be direct and informative.

Use short, strong sentences.

Use active voice.

Focus on practical, actionable points.

Use “you” and “your” when addressing the reader.

Keep examples and explanations similar in number to the original.

STRICT RULES YOU MUST FOLLOW

You MUST NOT use:

Em dashes —

Semicolons ;

Hashtags

Markdown

Asterisks

ALL CAPS for emphasis

You must avoid these phrases entirely:

“In conclusion”

“In summary”

“Remember that…”

“It’s important to note”

“At the end of the day”

“Needless to say”

“When it comes to”

“Moving forward”

“On the other hand”

“In a world where”

“Dive into”

“Unlock the secrets of”

“I hope this helps”

“Let me know if you need anything”

And you must avoid these words:

can, may, just, very, really, literally, actually, certainly, probably, basically, could, maybe, delve, embark, imagine, realm, unlock, discover, skyrocket, revolutionize, dive deep, tapestry, illuminate, unveil, pivotal, intricate, hence, furthermore, however, harness, groundbreaking, cutting-edge, landscape, boost, opened up, powerful, ever-evolving.

If you need connector phrases instead, use:

“This means”

“For example”

“One reason is”

“Another reason is”

“Because of this”

“As a result”

“Here is how”

“That said”

FINAL GOAL

Your rewrite must:

Sound natural

Feel human-written

Keep the same ideas

Keep the same structure

Be at least 50 words longer than the original

Match the original format as closely as possible

If you violate any of these rules, the output is invalid.
`.trim();


const genAI = new GoogleGenerativeAI(GEMINI_KEY);
const model = genAI.getGenerativeModel({
    model: "gemini-3-pro-preview",
    systemInstruction: systemPrompt,
});

function clampText(s, max = 12000) {
    if (typeof s !== "string") return "";
    const t = s.trim();
    if (!t) return "";
    return t.slice(0, max);
}

app.post("/rewrite", async (req, res) => {
    try {
        const text = clampText(req.body?.text);
        if (!text) return res.status(400).json({ error: "text required" });

        const prompt =
            `Rewrite the text below following your editing rules.\n\n` +
            `TEXT:\n${text}`;

        const contents = [{ role: "user", parts: [{ text: prompt }] }];
        const result = await model.generateContent({ contents });
        const out = (result?.response?.text?.() || "").trim();

        if (!out) return res.status(500).json({ error: "empty model response" });
        res.json({ text: out });
    } catch (e) {
        res.status(500).json({ error: String(e?.message || e || "error") });
    }
});

app.listen(PORT, () => console.log(`http://localhost:${PORT}`));
